const fs = require('fs');
const path = require('path');

const srcDir = path.join(__dirname, 'src');

const files = {
  'src/data/mock/projects.ts': `export const mockProjects = [\n  { id: '1', title: 'Saklan Residence', location: 'İstanbul / Kadıköy', category: 'Konut', description: 'Lüks rezidans projesi.', image: 'https://images.unsplash.com/photo-1600607686527-6fb886090705?auto=format&fit=crop&q=80' },\n  { id: '2', title: 'Saklan Villa', location: 'Muğla / Bodrum', category: 'Villa', description: 'Deniz manzaralı villalar.', image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&q=80' },\n  { id: '3', title: 'Saklan Business Center', location: 'İstanbul / Levent', category: 'Ticari', description: 'Modern iş merkezi.', image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&q=80' },\n  { id: '4', title: 'Saklan Modern Homes', location: 'İzmir / Karşıyaka', category: 'Konut', description: 'Aile dostu yaşam alanı.', image: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&q=80' }\n];\n`,
  'src/data/mock/realEstateListings.ts': `export const mockRealEstate = [\n  { id: '1', title: 'Lüks Deniz Manzaralı Daire', price: '12.500.000 TL', location: 'Kadıköy, Moda', rooms: '3+1', size: '145 m²', type: 'Satılık Daire', image: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&q=80' },\n  { id: '2', title: 'Havuzlu Müstakil Villa', price: '45.000.000 TL', location: 'Bodrum, Yalıkavak', rooms: '5+2', size: '350 m²', type: 'Villa', image: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&q=80' }\n];\n`,
  'src/data/mock/vehicleListings.ts': `export const mockVehicles = [\n  { id: '1', title: 'Mercedes-Benz C 200', price: '3.250.000 TL', year: '2023', km: '15.000 km', fuel: 'Benzin', gear: 'Otomatik', location: 'İstanbul', image: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&q=80' },\n  { id: '2', title: 'BMW 520i', price: '4.100.000 TL', year: '2024', km: '5.000 km', fuel: 'Hibrit', gear: 'Otomatik', location: 'Ankara', image: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&q=80' }\n];\n`,
  'src/pages/About/index.tsx': `export default function About() {\n  return (\n    <div className="max-w-7xl mx-auto px-4 py-16">\n      <h1 className="text-4xl font-light mb-8">Hakkımızda</h1>\n      <div className="prose prose-lg max-w-none text-gray-600">\n        <p className="mb-6">Saklan İnşaat olarak yılların verdiği tecrübe ile sektörde öncü olmaya devam ediyoruz. Amacımız sadece binalar değil, yaşam alanları inşa etmektir.</p>\n        <h2 className="text-2xl font-medium text-gray-900 mt-12 mb-4">Misyonumuz</h2>\n        <p className="mb-6">Müşterilerimize en yüksek kalitede yaşam alanları sunmak ve projelerimizi zamanında teslim etmek.</p>\n        <h2 className="text-2xl font-medium text-gray-900 mt-12 mb-4">Vizyonumuz</h2>\n        <p>Sektördeki yenilikleri takip ederek, sürdürülebilir ve modern mimariyi her projemize entegre etmek.</p>\n      </div>\n    </div>\n  );\n}\n`,
  'src/pages/Services/index.tsx': `export default function Services() {\n  const services = ['Konut Projeleri', 'Villa Projeleri', 'Ticari Yapılar', 'Anahtar Teslim Projeler', 'Tadilat / Renovasyon', 'Proje Yönetimi'];\n  return (\n    <div className="max-w-7xl mx-auto px-4 py-16">\n      <h1 className="text-4xl font-light mb-12">Hizmetlerimiz</h1>\n      <div className="grid grid-cols-1 md:grid-cols-3 gap-8">\n        {services.map((s, i) => (\n          <div key={i} className="bg-gray-50 p-8 rounded-lg border border-gray-100 hover:shadow-md transition-shadow">\n            <h3 className="text-xl font-medium mb-4">{s}</h3>\n            <p className="text-gray-600 font-light">Profesyonel ekibimizle size en iyi hizmeti sunmak için buradayız. Detaylı bilgi için bizimle iletişime geçin.</p>\n          </div>\n        ))}\n      </div>\n    </div>\n  );\n}\n`,
  'src/App.tsx': `import { BrowserRouter, Routes, Route } from 'react-router-dom';\nimport MainLayout from './components/layout/MainLayout';\nimport Home from './pages/Home';\nimport About from './pages/About';\nimport Services from './pages/Services';\nimport Projects from './pages/Projects';\nimport RealEstate from './pages/RealEstate';\nimport Automotive from './pages/Automotive';\n\nfunction App() {\n  return (\n    <BrowserRouter>\n      <Routes>\n        <Route path="/" element={<MainLayout />}>\n          <Route index element={<Home />} />\n          <Route path="hakkimizda" element={<About />} />\n          <Route path="hizmetler" element={<Services />} />\n          <Route path="projeler" element={<Projects />} />\n          <Route path="emlak" element={<RealEstate />} />\n          <Route path="otomotiv" element={<Automotive />} />\n        </Route>\n      </Routes>\n    </BrowserRouter>\n  );\n}\n\nexport default App;\n`,
};

Object.entries(files).forEach(([filepath, content]) => {
  const fullPath = path.join(__dirname, filepath);
  const dir = path.dirname(fullPath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
  fs.writeFileSync(fullPath, content);
});
