const fs = require('fs');
const path = require('path');

const srcDir = path.join(__dirname, 'src');

const filesToCreate = {
  'src/index.css': `@tailwind base;\n@tailwind components;\n@tailwind utilities;\n\nbody {\n  @apply bg-gray-50 text-gray-900 font-sans;\n}\n`,
  'src/main.tsx': `import React from 'react';\nimport ReactDOM from 'react-dom/client';\nimport App from './App.tsx';\nimport './index.css';\n\nReactDOM.createRoot(document.getElementById('root')!).render(\n  <React.StrictMode>\n    <App />\n  </React.StrictMode>,\n);\n`,
  'src/App.tsx': `import { BrowserRouter, Routes, Route } from 'react-router-dom';\nimport MainLayout from './components/layout/MainLayout';\nimport Home from './pages/Home';\nimport Projects from './pages/Projects';\nimport RealEstate from './pages/RealEstate';\nimport Automotive from './pages/Automotive';\n\nfunction App() {\n  return (\n    <BrowserRouter>\n      <Routes>\n        <Route path="/" element={<MainLayout />}>\n          <Route index element={<Home />} />\n          <Route path="projeler" element={<Projects />} />\n          <Route path="emlak" element={<RealEstate />} />\n          <Route path="otomotiv" element={<Automotive />} />\n        </Route>\n      </Routes>\n    </BrowserRouter>\n  );\n}\n\nexport default App;\n`,
  'src/components/layout/MainLayout.tsx': `import { Outlet } from 'react-router-dom';\nimport Navbar from './Navbar';\nimport Footer from './Footer';\n\nexport default function MainLayout() {\n  return (\n    <div className="min-h-screen flex flex-col">\n      <Navbar />\n      <main className="flex-grow">\n        <Outlet />\n      </main>\n      <Footer />\n    </div>\n  );\n}\n`,
  'src/components/layout/Navbar.tsx': `import { Link } from 'react-router-dom';\nimport { Menu } from 'lucide-react';\n\nexport default function Navbar() {\n  return (\n    <header className="bg-white shadow-sm sticky top-0 z-50">\n      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 h-20 flex items-center justify-between">\n        <Link to="/" className="text-2xl font-bold tracking-tighter text-primary">SAKLAN<span className="font-light">İNŞAAT</span></Link>\n        <nav className="hidden md:flex space-x-8">\n          <Link to="/" className="text-gray-600 hover:text-primary transition-colors">Ana Sayfa</Link>\n          <Link to="/hakkimizda" className="text-gray-600 hover:text-primary transition-colors">Hakkımızda</Link>\n          <Link to="/hizmetler" className="text-gray-600 hover:text-primary transition-colors">Hizmetler</Link>\n          <Link to="/projeler" className="text-gray-600 hover:text-primary transition-colors">Projeler</Link>\n          <Link to="/emlak" className="text-primary font-medium hover:text-primary-dark transition-colors">Emlak</Link>\n          <Link to="/otomotiv" className="text-primary font-medium hover:text-primary-dark transition-colors">Otomotiv</Link>\n          <Link to="/iletisim" className="text-gray-600 hover:text-primary transition-colors">İletişim</Link>\n        </nav>\n        <button className="md:hidden p-2"><Menu className="w-6 h-6" /></button>\n      </div>\n    </header>\n  );\n}\n`,
  'src/components/layout/Footer.tsx': `export default function Footer() {\n  return (\n    <footer className="bg-primary text-white py-12">\n      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">\n        <div className="grid grid-cols-1 md:grid-cols-4 gap-8">\n          <div>\n            <h3 className="text-2xl font-bold tracking-tighter mb-4">SAKLAN<span className="font-light">İNŞAAT</span></h3>\n            <p className="text-sm text-gray-300">Modern ve premium yaşam alanları inşa ediyoruz.</p>\n          </div>\n          <div>\n            <h4 className="font-semibold mb-4">Hızlı Linkler</h4>\n            <ul className="space-y-2 text-sm text-gray-300">\n              <li><a href="/hakkimizda">Hakkımızda</a></li>\n              <li><a href="/projeler">Projeler</a></li>\n              <li><a href="/emlak">Emlak İlanları</a></li>\n            </ul>\n          </div>\n          <div>\n             <h4 className="font-semibold mb-4">İletişim</h4>\n             <ul className="space-y-2 text-sm text-gray-300">\n               <li>info@saklaninsaat.com</li>\n               <li>+90 532 000 00 00</li>\n             </ul>\n          </div>\n        </div>\n        <div className="border-t border-white/20 mt-12 pt-8 text-center text-sm text-gray-400">\n          © {new Date().getFullYear()} Saklan İnşaat. Tüm hakları saklıdır.\n        </div>\n      </div>\n    </footer>\n  );\n}\n`,
  'src/pages/Home/index.tsx': `export default function Home() {\n  return (\n    <div className="animate-in fade-in duration-500">\n      <section className="relative h-[80vh] flex items-center justify-center overflow-hidden bg-gray-900">\n        <div className="absolute inset-0 z-0 opacity-60 bg-[url('https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&q=80')] bg-cover bg-center" />\n        <div className="relative z-10 text-center px-4 max-w-4xl mx-auto">\n          <h1 className="text-5xl md:text-7xl font-bold text-white tracking-tight mb-6">\n            Geleceği İnşa Ediyoruz\n          </h1>\n          <p className="text-xl text-gray-200 mb-10 font-light">\n            Modern mimari, premium kalite ve güven veren projelerle hayallerinizi gerçeğe dönüştürüyoruz.\n          </p>\n          <div className="flex flex-col sm:flex-row gap-4 justify-center">\n            <button className="bg-primary hover:bg-primary-dark text-white px-8 py-4 rounded-none text-lg transition-colors">\n              Projelerimizi İncele\n            </button>\n            <button className="bg-white/10 backdrop-blur-md hover:bg-white/20 text-white border border-white/30 px-8 py-4 rounded-none text-lg transition-all">\n              Emlak İlanları\n            </button>\n          </div>\n        </div>\n      </section>\n    </div>\n  );\n}\n`,
  'src/pages/Projects/index.tsx': `export default function Projects() {\n  return (\n    <div className="max-w-7xl mx-auto px-4 py-16">\n      <h1 className="text-4xl font-light mb-12">Projelerimiz</h1>\n      <div className="grid grid-cols-1 md:grid-cols-2 gap-8">\n        <div className="group cursor-pointer">\n          <div className="aspect-[4/3] bg-gray-200 overflow-hidden mb-4">\n            <img src="https://images.unsplash.com/photo-1600607686527-6fb886090705?auto=format&fit=crop&q=80" alt="Saklan Residence" className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-700" />\n          </div>\n          <h3 className="text-2xl font-medium mb-2">Saklan Residence</h3>\n          <p className="text-gray-600 font-light">İstanbul / Kadıköy</p>\n        </div>\n        <div className="group cursor-pointer">\n          <div className="aspect-[4/3] bg-gray-200 overflow-hidden mb-4">\n            <img src="https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&q=80" alt="Saklan Villa" className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-700" />\n          </div>\n          <h3 className="text-2xl font-medium mb-2">Saklan Villa</h3>\n          <p className="text-gray-600 font-light">Muğla / Bodrum</p>\n        </div>\n      </div>\n    </div>\n  );\n}\n`,
  'src/pages/RealEstate/index.tsx': `export default function RealEstate() {\n  return (\n    <div className="bg-gray-50 min-h-screen py-12">\n      <div className="max-w-7xl mx-auto px-4">\n        <h1 className="text-3xl font-semibold mb-8 text-primary">Saklan Emlak</h1>\n        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">\n          {[1,2,3,4,5,6].map(i => (\n            <div key={i} className="bg-white rounded-lg shadow-sm border border-gray-100 overflow-hidden hover:shadow-md transition-shadow">\n              <div className="aspect-video bg-gray-200">\n                 <img src="https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&q=80" alt="Emlak" className="w-full h-full object-cover" />\n              </div>\n              <div className="p-4">\n                <div className="text-primary font-bold text-xl mb-2">12.500.000 TL</div>\n                <h3 className="font-medium text-gray-900 mb-1">Lüks Deniz Manzaralı Daire</h3>\n                <p className="text-sm text-gray-500 mb-4">Kadıköy, Moda</p>\n                <div className="flex text-sm text-gray-600 space-x-4">\n                  <span>3+1</span>\n                  <span>145 m²</span>\n                </div>\n              </div>\n            </div>\n          ))}\n        </div>\n      </div>\n    </div>\n  );\n}\n`,
  'src/pages/Automotive/index.tsx': `export default function Automotive() {\n  return (\n    <div className="bg-gray-50 min-h-screen py-12">\n      <div className="max-w-7xl mx-auto px-4">\n        <h1 className="text-3xl font-semibold mb-8 text-primary">Saklan Otomotiv</h1>\n        <div className="grid grid-cols-1 md:grid-cols-4 gap-6">\n          {[1,2,3,4].map(i => (\n            <div key={i} className="bg-white rounded-lg shadow-sm border border-gray-100 overflow-hidden hover:shadow-md transition-shadow">\n              <div className="aspect-[4/3] bg-gray-200">\n                <img src="https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&q=80" alt="Araç" className="w-full h-full object-cover" />\n              </div>\n              <div className="p-4">\n                <h3 className="font-bold text-gray-900 mb-1">Mercedes-Benz C 200</h3>\n                <p className="text-xs text-gray-500 mb-2">2023 • 15.000 km • Benzin</p>\n                <div className="text-primary font-bold">3.250.000 TL</div>\n              </div>\n            </div>\n          ))}\n        </div>\n      </div>\n    </div>\n  );\n}\n`
};

Object.entries(filesToCreate).forEach(([filepath, content]) => {
  const fullPath = path.join(__dirname, filepath);
  const dir = path.dirname(fullPath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
  fs.writeFileSync(fullPath, content);
});
